### ISSUE TITLE
NoClassDefFoundError: jline/CompletionHandler

### ISSUE THREAD

**Issue by klopfdreh** [grails/grails-maven#65]
Hi,

if I run the maven plugin with the following configuration I got a NoClassDefFoundError:

```xml
	<build>
		<plugins>
			<plugin>
				<groupId>org.grails</groupId>
				<artifactId>grails-maven-plugin</artifactId>
				<version>2.4.4</version>
				<configuration>
					<grailsVersion>2.2.4</grailsVersion>
				</configuration>
			</plugin>
		</plugins>
	</build>
```

```java
Caused by: java.lang.ClassNotFoundException: jline.CompletionHandler
	at org.grails.launcher.RootLoader.findClass(RootLoader.java:147)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.grails.launcher.RootLoader.loadClass(RootLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more
```

**Comment by klopfdreh** [comment]
By the way:  is there something I can do to invoke the following command?
```java
grails doc
```

**Comment by igorbljahhin** [comment]
Same here for the following configuration:

    <plugin>
        <groupId>org.grails</groupId>
        <artifactId>grails-maven-plugin</artifactId>
        <version>2.4.6</version>
        <extensions>true</extensions>
        <configuration>
            <grailsVersion>2.3.0</grailsVersion>
            <showStacktrace>true</showStacktrace>
        </configuration>
        <executions>
            <execution>
                <phase>prepare-package</phase>
                <goals>
                    <goal>maven-war</goal>
                </goals>
            </execution>
            <execution>
                <id>grails-unit-tests</id>
                <phase>test</phase>
                <goals>
                    <goal>exec</goal>
                </goals>
                <configuration>
                    <command>test-app</command>
                    <args>-unit -xml --non-interactive</args>
                </configuration>
            </execution>
        </executions>
    </plugin>

Maven version:

> mvn --version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T14:57:37+03:00)
Maven home: C:\opt\apache-maven-3.3.3
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_79\jre
Default locale: en_US, platform encoding: Cp1251
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "windows"
