### ISSUE TITLE
it does not compile with springframework 5.0.x or up

### ISSUE THREAD

**Issue by cliffwy** [grails/grails-maven#81]
New springfrawework removed the class  org.springframework.util.Log4jConfigurer. so the it failed when build the project.
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-maven-compile of goal org.grails:grails-maven-plugin:2.4.6:maven-compile failed: java.lang.ClassNotFoundEx           ception: org.springframework.util.Log4jConfigurer
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.springframework.util.Log4jConfigurer
        at org.grails.maven.plugin.tools.AbstractGrailsRuntime.createGrailsLauncher(AbstractGrailsRuntime.java:38)
        at org.grails.maven.plugin.tools.DefaultGrailsRuntime.run(DefaultGrailsRuntime.java:17)
        at org.grails.maven.plugin.AbstractGrailsMojo.runGrails(AbstractGrailsMojo.java:372)
        at org.grails.maven.plugin.AbstractGrailsMojo.runGrails(AbstractGrailsMojo.java:334)
        at org.grails.maven.plugin.MvnCompileMojo.execute(MvnCompileMojo.java:41)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
Caused by: java.lang.ClassNotFoundException: org.springframework.util.Log4jConfigurer
        at org.grails.launcher.RootLoader.findClass(RootLoader.java:147)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.grails.launcher.RootLoader.loadClass(RootLoader.java:119)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.grails.maven.plugin.tools.AbstractGrailsRuntime.addLoggingJarsToRootLoader(AbstractGrailsRuntime.java:71)
        at org.grails.maven.plugin.tools.AbstractGrailsRuntime.createGrailsLauncher(AbstractGrailsRuntime.java:36)

**Comment by jambus289** [comment]
May i know what is the solution to fix the log4jconfigurer part of spring dependency upgrade in grails app
